# fly.toml app configuration file generated for subscribeme-backend on 2023-06-03T03:36:46+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "subscribeme-backend"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  AUTH_SECRET = "SUPERSECRETKODEBYSUBSCRIBEME"
  DB_HOST = "subscribe-me.internal"
  DB_NAME = "subscribeme"
  DB_PASSWORD = "4LCaBgTqKGN2yyH"
  DB_PORT = "5433"
  DB_USER = "postgres"
  PORT = "8080"
  SIAKNG_PASSWORD = "airiex4L"
  SIAKNG_USERNAME = "ppl-kayu"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
